### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by p4rkrs** [nsaovh/rcgp#1]
Hi,

You should credits https://github.com/MeyerHallot/Anime-Girls-Holding-Programming-Books, it's from here that you getting your images right?

Add it to the footer of the website and in the README please.

**Comment by r33int** [comment]
Two sugar

**Comment by luclu7** [comment]
too fast for you

**Comment by p4rkrs** [comment]
1% of your user will see that github repo, add it in the footer too please.
